blank_issues_enabled: false
contact_links:
- name: Questions, feature requests, and more ðŸ’¬
  url: https://github.com/bytemare/opaque/discussions
  about: Do you need help? Did you make something with OPAQUE? Do you have an idea? Tell us about it!